version: "3"

networks:
  backend:
  traefik_net:
    external: true

services:
  node_server:
    build: .
    labels:
     - "traefik.enable=true"
     - "traefik.frontend.rule=Host:terminals.mse.hn"
     - "traefik.docker.network=traefik_net"
     - "traefik.port=8000"
    networks:
     - traefik_net
     - backend

  mongo_db:
    image: mongo:latest
    labels:
      - "traefik.enable=false"
    networks: 
      - backend