version: "3"

networks:
  backend:
  traefik_net:
    external: true

services:
  node_server:
    build: .
    labels:
     - "traefik.enable=true"
     - "traefik.frontend.rule=Host:terminals.mse.hn"
     - "traefik.docker.network=traefik_net"
     - "traefik.port=8080"
    networks:
     - traefik_net
     - backend
